### ISSUE TITLE
GetObject always fails from API

### ISSUE THREAD

**Issue by douggreen** [oblakstudio/ddev-minio#18]
Aws\S3\StreamWrapper::openReadStream() always throws an Exception 

```
Error executing "GetObject" on "https://MYSITE.com:10101/files/s3fs-public/somefile.jpg"; AWS HTTP error: An error was encountered while creating the response. 
```
I uploaded files using the Stream Wrapper. I can see the files from the console and web interface. I can download the file with the web interface.

Do you have any suggestions?

**Comment by seebeen** [comment]
I need more details on the implementation.
Which language, which client library?

If possible, a MRR would be awesome 😊

**Comment by douggreen** [comment]
What is a MRR?

I have two small ddev setups, Drupal 7/10, s3fs, and ddev minio. The problem exists on the Drupal 7 site. If I can't figure out the problem, I'll push these to GitHub for you to review.

**Comment by douggreen** [comment]
Closing this issue, it's something in my site setup. I now have the bare bones D7 site working.
