### ISSUE TITLE
mc-config.json doesn't work

### ISSUE THREAD

**Issue by timkelty** [oblakstudio/ddev-minio#30]
As far as I can tell, the `mc-config.json` file is not taking effect as expected.

```
ddev get oblakstudio/ddev-minio
ddev restart
ddev mc alias ls
```
Outputs: (Notice the warning about tmp configuration, and that there is no `minio` key)
```
mc: Configuration written to `/tmp/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/tmp/.mc/share`.
mc: Initialized share uploads `/tmp/.mc/share/uploads.json` file.
mc: Initialized share downloads `/tmp/.mc/share/downloads.json` file.
gcs
  URL       : https://storage.googleapis.com
  AccessKey : YOUR-ACCESS-KEY-HERE
  SecretKey : YOUR-SECRET-KEY-HERE
  API       : S3v2
  Path      : dns

local
  URL       : http://localhost:9000
  AccessKey :
  SecretKey :
  API       :
  Path      : auto

play
  URL       : https://play.min.io
  AccessKey : Q3AM3UQ867SPQQA43P2F
  SecretKey : zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  API       : S3v4
  Path      : auto

s3
  URL       : https://s3.amazonaws.com
  AccessKey : YOUR-ACCESS-KEY-HERE
  SecretKey : YOUR-SECRET-KEY-HERE
  API       : S3v4
  Path      : dns
```

If you create it manually:

```
ddev mc alias set minio  http://localhost:10101 ddevminio ddevminio
ddev mc alias ls
```

It will be listed as expected, and you can go on to use it (eg `mc mb minio/my-bucket`).
As expected, the alias and bucket will go away with a `ddev restart`, as they are in tmp.

It also may make sense to make the alias `local`, as this seems to be the default?

**Comment by seebeen** [comment]
There was a problem with a config directory env var. I fixed that and some other minor annoyances.

Regarding the alias - probably will rename, after they bring the changes from the linux version to the docker one so I can rework the entire addon.

**Comment by timkelty** [comment]
Thanks!
