### ISSUE TITLE
Using `ports` means that only one project can use this without modification

### ISSUE THREAD

**Issue by rfay** [oblakstudio/ddev-minio#5]
Congrats on the new add-on! Thanks for maintaining this.

I notice that you use `ports` in the docker-compose.*.yaml, that means this will only be able to be used on one project without modification. There are better ways. You already have things exposed, so you shouldn't need `ports` for any HTTP port. You would use HTTP_EXPOSE and HTTPS_EXPOSE, but you already have those in play. What is port 9000 for anyway?

(Also note that port 9000 often conflicts with other usages, like php-fpm, so it's usually a prescription for trouble to use 9000 for anything)

**Comment by seebeen** [comment]
I think that might be an artifact of the development. I forgot to remove it.
9000 is only needed internaly among instances, not externally on the host.

I'll remove it asap!

**Comment by rfay** [comment]
Fixed in https://github.com/oblakstudio/ddev-minio/pull/8

**Comment by rfay** [comment]
Thanks!
