### ISSUE TITLE
Please get tests going, and nightly tests

### ISSUE THREAD

**Issue by rfay** [oblakstudio/ddev-minio#6]
For these add-ons to be successful, some decent automated tests (and run nightly) are critical. Please enable them and make sure the tests are good.

**Comment by seebeen** [comment]
Hello,

There are tests. Both for stable, and Edge and HEAD.
I'm running stable on my custom runner which always has a stable version of ddev for my other projects, and HEAD and edge tests on the github runners.

Stable is run on my runner because it's much much faster than github runners

Feel free to check out the [workflows](https://github.com/oblakstudio/ddev-minio/tree/master/.github/workflows).

**Comment by seebeen** [comment]
No, for stable I'm using a custom runner maintained by me. It's always on latest stable DDEV version.
It saves **a lot** of time during testing. Entire test suite is complete in 1m (compared to 5m+ for github runners).  
For bleeding Edge DDEV, I'm using github hosted runners.

In any case, the tests are there - and addon works.

**Comment by rfay** [comment]
The problem with local runners is the maintenance factor. I know because we have to use buildkite local runners with DDEV for macOS and Windows + WSL2. And I'm the one who has to reboot them when they fail. And there's the visibility factor - nobody else can contribute. That's where Github Actions (or CircleCI, etc.) shine: They're maintainable by a team, and their results are visible and repeatable.

> In any case, the tests are there - and addon works.

The idea of open source and Ci is not just that "it works", but rather than a team or organization can verify that it works and be confident that it will work in 1 year or 5 years.

**Comment by rfay** [comment]
Well, it's your add-on and can be done any way you want until the point you want to promote it to an official add-on. 

But yes, online runners mean more visibility and a wider community being able to maintain and improve it.

**Comment by rfay** [comment]
I note that the tests are failing consistently. Could you please get them working? 

I recommend not using the :latest tag for minio/minio, because things can change underneath you.

**Comment by douggreen** [comment]
You can close this issue. It seems to have been a problem with my local setup. I did a bunch of cleanup (removed ~/.lima, ~/.colima, and ~/.ddev) and got it working.

**Comment by rfay** [comment]
No, this issue can't be closed. The tests are failing every night.

**Comment by seebeen** [comment]
Tests reworked and fully operational

**Comment by rfay** [comment]
Thanks!
